### ISSUE TITLE
Poor performance on Nvidia GPU

### ISSUE THREAD

**Issue by vtenfys** [SteveBirtles/orthoengine#2]
I get a much lower FPS running OrthoEngine on my GTX 850M than I get when using my Intel graphics on the same laptop. Any idea what could be the problem?

(I got it to run in the end - not exactly sure what was the problem since all I did was reinstall Go and TDM-GCC, except I put them in the default locations.)

**Comment by SteveBirtles** [comment]
Default locations - I'm not surprised that was the solution :) Good news though.

So... as far as GPU performance goes, it's either a library issue (faiface pixel) or a square texture issue. If we resize the png files to 2048x2048 (or other value of 2 to the power n) it might work better... Sadly can't do any coding today.

This'll need changing:

const tileSheetWidth = 2048
const tileSheetHeight = 1280
const totalTiles = (tileSheetWidth /128)*(tileSheetHeight /128)

const spriteSheetWidth = 1280
const spriteSheetHeight = 1024
const totalSprites = (spriteSheetWidth /128)*(spriteSheetHeight /128)

**Comment by SteveBirtles** [comment]
Did that work?

**Comment by vtenfys** [comment]
Nope, I'm still getting ~30 FPS on my Nvidia GTX card compared to ~60 on my Intel HD card
